import addTapClass       from './module/add_tap_class.js';
// import boxLink           from './module/box_link.js';
import currentLink       from './module/current_link.js';
import disableTelLink    from './module/disable_tel_link.js';
import globalNav         from './module/glovalnav.js';
// import imgLiquid         from './module/img_liquid.js';
import magnificPopup     from './module/magnific_popup.js';
// import matchHeight       from './module/match_height.js';
// import onPortraitChange  from './module/on_portrait_change.js';
import popup             from './module/popup.js';
// import replaceSrc        from './module/replase_src.js';
// import rollover          from './module/rollover.js';
import anchorLink        from './module/scroll_anchor.js';
// import scrollTable       from './module/scroll_table.js';
import scrollHeaderEffect from './module/scroll_header_effect.js';
// import tab               from './module/tab.js';
import toggole           from './module/toggle.js';
import toggoleCategory   from './module/toggle_category.js';
import onMediaQuery      from './on_media_query.js';